@startuml
actor Buyer
actor Seller
control "Algo Escrow (Buy)\nStateless" as AlgoEscrow
database "Algo OB\nStateful" as AlgoOB
note over AlgoEscrow: ALGO reserved for buy

group "Placing an Algo Escrow Order: Orderbook Opt-In & Registration"
autonumber 0
Buyer -> AlgoEscrow: Pay from order creator to escrow
note right: send X ALGO\nto pay for Y ASA
AlgoEscrow -> AlgoOB: [if necessary] App opt-in
note left: TEAL attached\nfor spend approval
Buyer -> Buyer: [if necessary] Opt-in to ASA to buy
end

@enduml
