@startuml
actor "Buyer \n(Algo Escrow Owner)" as Buyer
control "Algo Escrow (Buy Order)\nStateless" as AlgoEscrow
database "Algo Order Book\nStateful" as AlgoOB
note over AlgoEscrow: Algo reserved for buy

group "Algo Escrow Cancel-Order - Initiated By Algo Escrow Owner"
autonumber 0
AlgoEscrow -> AlgoOB: app 'clear state' call
note left: TEAL attached\nfor approval
AlgoEscrow -> Buyer: Algo 'close-to' account - 0 Algo send\nw/ close-to of balance to owner
note right: X Algo refunded to Buyer\nvia escrow 'close'.\nTEAL attached\nfor spend approval
Buyer -> Buyer: 0 Algo payment\nto prove ownership
end

@enduml
