@startuml
actor "Seller \n(ASA Escrow Owner)" as Seller
control "ASA Escrow (Sell Order)\nStateless" as ASAEscrow
database "ASA Order Book\nStateful" as ASAOB
note over ASAEscrow: Min .5 Algo bal.\n+ ASA to sell

group "ASA Escrow Cancel-Order - Initiated By ASA Escrow Owner"
autonumber 0
ASAEscrow -> ASAOB: app call to clear
note left: TEAL attached\nfor approval
ASAEscrow -> Seller: ASA 'close-to' to owner
note right: TEAL attached\nfor approval
ASAEscrow -> Seller: refund txn fees (Algo 'close-to')
note right: TEAL attached\nfor approval
Seller -> Seller: 0 Algo payment\nto prove ownership
end

@enduml
