@startuml
actor Buyer
actor Seller
control "ASA Escrow (Sell)\nStateless" as ASAEscrow
database "ASA OB\nStateful" as ASAOB
note over ASAEscrow: Min .5 ALGO bal.\n+ ASA to sell

group "ASA Escrow Pay (Order Exec)\nWith Closeout - Initiated by ASA Buyer"
autonumber 0
ASAEscrow -> ASAOB: app call
note left: TEAL attached\nfor approval
Buyer -> Seller: ALGO payment\nof partial order amount
Buyer -> Buyer: [if necessary] Opt-in to ASA to buy
ASAEscrow -> Buyer: Asset send\nof full sell amount\nto buyer
note right: Closes out remaining ASA balance to Seller
ASAEscrow -> Seller: Closeout of minimum algo balance
end

@enduml
