@startuml
actor "Seller \n(ASA Escrow Owner)" as Seller
control "ASA Escrow (Sell Order)\nStateless" as ASAEscrow
database "ASA Order Book\nStateful" as ASAOB
note over ASAEscrow: Min .5 Algo bal.\n+ ASA to sell

group "Placing an ASA Escrow Order: ASA Order Book Opt-in"
autonumber 0
Seller -> ASAEscrow: Send future .5 txn fees into escrow
ASAEscrow -> ASAOB: App opt-in
note left: TEAL attached\nfor approval
ASAEscrow -> ASAEscrow: ASA opt-in
note right: TEAL attached\nfor approval
Seller -> ASAEscrow: Send ASA to be sold to escrow
end

@enduml
