@startuml
actor Buyer
actor Seller
control "Algo Escrow (Buy)\nStateless" as AlgoEscrow
control "ASA Escrow (Sell)\nStateless" as ASAEscrow
database "Algo OB\nStateful" as AlgoOB
database "ASA OB\nStateful" as ASAOB
note over AlgoEscrow: ALGO reserved for buy
note over ASAEscrow: Min .5 ALGO bal.\n+ ASA to sell

group "Placing an Algo Escrow Order: Orderbook Opt-In & Registration"
autonumber 0
Buyer -> AlgoEscrow: Pay from order creator to escrow
note right: send X ALGO\nto pay for Y ASA
AlgoEscrow -> AlgoOB: [if necessary] App opt-in
note left: TEAL attached\nfor spend approval
Buyer -> Buyer: [if necessary] Opt-in to ASA to buy
end

group "Algo Escrow Cancel-Order - Initiated By ASA Escrow Owner"
autonumber 0
AlgoEscrow -> AlgoOB: app 'clear state' call
note left: TEAL attached\nfor spend approval
AlgoEscrow -> Buyer: ALGO 'close-to' account - 0 ALGO send\nw/ close-to creator
note right: X ALGO refunded to Buyer\nvia escrow 'close'\nTEAL attached\nfor spend approval
Buyer -> Buyer: 0 ALGO payment\nto ensure ownership
end

group "Placing an ASA Escrow Order: ASA Orderbook Opt-in"
autonumber 0
Seller -> ASAEscrow: Send future .5 txn fees into escrow
ASAEscrow -> ASAOB: App opt-in
note left: TEAL attached\nfor spend approval
ASAEscrow -> ASAEscrow: ASA opt-in
note right: TEAL attached\nfor spend approval
Seller -> ASAEscrow: Send ASA to be sold to escrow
end

group "ASA Escrow Cancel-Order - Initiated By ASA Escrow Owner"
autonumber 0
ASAEscrow -> ASAOB: app call to clear
note left: TEAL attached\nfor spend approval
ASAEscrow -> Seller: ASA 'close-to'
note right: TEAL attached\nfor spend approval
ASAEscrow -> Seller: refund txn fees (ALGO 'close-to')
note right: TEAL attached\nfor spend approval
Seller -> Seller: 0 ALGO payment\nto ensure ownership
end

group "Algo Escrow Pay (Order Exec)\nwith Closeout - Initiated by ASA Seller"
autonumber 0
AlgoEscrow -> ASAOB: app call to closeout
note left: TEAL attached\nfor spend approval
AlgoEscrow -> Seller: ALGO payment\nof order amount
note right: TEAL attached\nfor spend approval
Seller -> Buyer: Asset send\nof sell amount\nto buy escrow owner
end

group "Algo Escrow Pay (Order Exec)\nPartial Exec. - Initiated by ASA Seller"
autonumber 0
AlgoEscrow -> ASAOB: app call
note left: TEAL attached\nfor spend approval
AlgoEscrow -> Seller: ALGO payment\nof partial order amount
note right: TEAL attached\nfor spend approval
Seller -> Buyer: Asset send\nof partial sell amount\nto buy escrow owner
note right: TEAL attached\nfor spend approval
Seller -> AlgoEscrow: fee refund transaction
end

group "Algo Escrow Pay (Order Exec)\nwith Closeout - Initiated by ASA Seller"
autonumber 0
AlgoEscrow -> ASAOB: app call to closeout
note left: TEAL attached\nfor spend approval
AlgoEscrow -> Seller: ALGO payment\nof order amount
note right: TEAL attached\nfor spend approval
Seller -> Buyer: Asset send\nof sell amount\nto buy escrow owner
end

group "ASA Escrow Pay (Order Exec)\nPartial Exec. - Initiated by ASA Buyer"
autonumber 0
ASAEscrow -> ASAOB: app call
note left: TEAL attached\nfor spend approval
Buyer -> Seller: ALGO payment\nof partial order amount
Buyer -> Buyer: [if necessary] Opt-in to ASA to buy
ASAEscrow -> Buyer: Asset send\nof partial sell amount\nto buy escrow owner
note right: TEAL attached\nfor spend approval
Buyer -> AlgoEscrow: fee refund transaction
end

group "ASA Escrow Pay (Order Exec)\nWith Closeout - Initiated by ASA Buyer"
autonumber 0
ASAEscrow -> ASAOB: app call
note left: TEAL attached\nfor spend approval
Buyer -> Seller: ALGO payment\nof partial order amount
Buyer -> Buyer: [if necessary] Opt-in to ASA to buy
ASAEscrow -> Buyer: Asset send\nof full sell amount\nto buy escrow owner
note right: TEAL attached\nfor spend approval
ASAEscrow -> Seller: Closeout of minimum algo balance
end
@enduml
