@startjson
{
    "dexidx:algod:round" : "algo round #",
    "dexidx:accounts:watched" : [
        "[SET]",
        "account 1",
        "account 2",
        "account 3..."
    ],
    "dexidx:account:{account X}" : "{account json} TTL 7d",
    "dexidx:account:{account Y}" : "{account json} TTL 7d",
    "dexidx:account:{account Z...}" : "{account json} TTL 7d",
    "dexidx:asset:info:{asset id x}" : "{asset json} TTL 1h",
    "dexidx:asset:info:{asset id y}" : "{asset json} TTL 1h",
    "dexidx:asset:info:{asset id z...}" : "{asset json} TTL 1h",
    "trade_history:assetId:{asset id x}" : "{trade history json} TTL 12h",
    "charts:assetId:{asset id y}" : "{charts json} TTL 12h",
    "orders:assetId:{asset id z}" : "{orders json} TTL 12h",
    "nonPriceAssetInfo:{asset id x}" : "{asset json} TTL 12h",
    "asset_by_id:assetId:{asset id y}" : "{asset json} TTL 12h",
    "trade_history:ownerAddr:{ownerAddr a}" : "{trade history json} TTL 12h",
    "orders:ownerAddr:{ownerAddr b}" : "{orders json} TTL 12h",
    "wallet_assets:orders:ownerAddr:{ownerAddr c}" : "{wallet assets json} TTL 12h",
    "recent_trade_info" : "{recent trade info json} TTL 12h"
}
@endjson